#!/usr/bin/env python3
"""Examples/Tutorial/** を実際に走らせ、実行結果画像を撮り直す。

各節のスケッチを `METAPHOR_PROBE=1 METAPHOR_VIEWER=1` で起動し、Probe が書く
`.metaphor/probe/current/frame.png` を
`docs/tutorial/images/{部番号}-{部スラッグ}/{節番号}-{節スラッグ}.png` へ配置する。
手で撮ったスクリーンショットは置かない（Issue #486 / docs/tutorial/README.md）。

    make tutorial-shots                     # 参照されている全節を撮り直す
    make tutorial-shots ARGS="--only 01-GettingStarted/03-SketchSkeleton"
    python3 scripts/generate-tutorial-shots.py --check   # 鮮度だけ調べる

## なぜ PNG のバイト比較で鮮度を見ないか

GPU レンダリングの出力は環境（GPU・ドライバ・OS）でビット単位には一致しない。
撮り直すたびに差分が出るので、`--check` は画像そのものではなく
`docs/tutorial/images/manifest.json` に記録した**撮影時のソースのハッシュ**と
現在のソースを突き合わせる。これで「コードを変えたのに画像を撮り直していない」
という実際に起きるドリフトだけを、GPU の無い CI ランナーでも検出できる。

撮影自体はローカルで行いコミットする（CI では走らせない）。
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CODE_DIR = REPO_ROOT / "Examples/Tutorial"
DOCS_DIR = REPO_ROOT / "docs/tutorial"
IMAGES_DIR = DOCS_DIR / "images"
MANIFEST = IMAGES_DIR / "manifest.json"

# 埋め込みマーカー（generate-tutorial-snippets.py と同じ書式）。本文が参照して
# いる節 = 画像が要る節、と定義する。
SNIPPET_RE = re.compile(r"^<!-- tutorial-snippet:\s*(?P<ref>\S+)\s*-->$")

# 指紋の材料から外すもの。ビルド生成物・IDE 設定・Probe の作業ディレクトリ・
# Finder のメタデータで、いずれも絵には影響しない（すべて gitignore 済み）。
EXCLUDED_NAMES = {".build", ".swiftpm", ".metaphor", ".DS_Store"}

# 起動から frame.png が書かれるまでの待ち時間。初回はシェーダーのコンパイルが
# 入るぶん遅い。
CAPTURE_TIMEOUT_SEC = 90.0
POLL_INTERVAL_SEC = 0.2


class ShotError(Exception):
    """撮影も検証もできない構成（利用者が直す必要がある）。"""


def referenced_refs() -> list[str]:
    """docs/tutorial/*.md が埋め込んでいる節を、登場順・重複排除で返す。"""
    refs: list[str] = []
    for doc in sorted(DOCS_DIR.glob("*.md")):
        if doc.name == "README.md":
            continue
        for line in doc.read_text(encoding="utf-8").split("\n"):
            matched = SNIPPET_RE.match(line)
            if matched and matched.group("ref") not in refs:
                refs.append(matched.group("ref"))
    return refs


def source_files(package_dir: Path) -> list[Path]:
    """指紋の材料。Swift だけでなくリソースも含める（#505）。"""
    files = []
    for path in package_dir.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(package_dir)
        if EXCLUDED_NAMES.intersection(relative.parts):
            continue
        files.append(path)
    return sorted(files, key=lambda p: p.relative_to(package_dir).as_posix())


def source_hash(package_dir: Path) -> str:
    """パッケージのソースとリソースから決まる指紋。撮り直しの要否はこれで判定する。

    絵を変えうるものはすべて材料にする。Swift だけを見ていた頃は、同梱画像や
    シェーダーを差し替えても `--check` が「最新」と答えていた（#505）。
    """
    digest = hashlib.sha256()
    for path in source_files(package_dir):
        digest.update(path.relative_to(package_dir).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def image_path_for(ref: str) -> Path:
    part, section = ref.split("/", 1)
    return IMAGES_DIR / part / f"{section}.png"


def load_manifest() -> dict:
    if not MANIFEST.is_file():
        return {}
    return json.loads(MANIFEST.read_text(encoding="utf-8")).get("shots", {})


def save_manifest(shots: dict) -> None:
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        "comment": (
            "Generated by scripts/generate-tutorial-shots.py. "
            "sourceHash is the fingerprint of the sketch the image was taken from."
        ),
        "shots": dict(sorted(shots.items())),
    }
    MANIFEST.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def capture(ref: str) -> dict:
    """1 節ぶん撮る。撮れた画像の manifest エントリを返す。"""
    package_dir = CODE_DIR / ref
    if not (package_dir / "Package.swift").is_file():
        raise ShotError(f"'{ref}' に対応する SwiftPM パッケージが無い")

    probe_dir = package_dir / ".metaphor/probe"
    output_dir = probe_dir / "current"
    shutil.rmtree(probe_dir, ignore_errors=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    # リクエストは**起動前**に置く。noLoop のスケッチは最初の 1 フレームしか
    # 描かないため、起動後に置いても処理する機会が来ない。
    request = {"id": f"tutorial-shot-{ref}", "label": ref, "scale": 1.0}
    tmp = probe_dir / "request.json.tmp"
    tmp.write_text(json.dumps(request), encoding="utf-8")
    tmp.replace(probe_dir / "request.json")  # 契約点 4: アトミックに置く

    print(f"  building {ref} ...", flush=True)
    build = subprocess.run(
        ["swift", "build"], cwd=package_dir, capture_output=True, text=True
    )
    if build.returncode != 0:
        raise ShotError(f"'{ref}' のビルドに失敗した:\n{build.stdout}\n{build.stderr}")

    env = dict(os.environ)
    env["METAPHOR_PROBE"] = "1"
    env["METAPHOR_VIEWER"] = "1"  # ヘッドレス（ウィンドウを開かない）

    print(f"  running  {ref} ...", flush=True)
    process = subprocess.Popen(
        ["swift", "run"],
        cwd=package_dir,
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
    )
    frame_png = output_dir / "frame.png"
    frame_json = output_dir / "frame.json"
    deadline = time.monotonic() + CAPTURE_TIMEOUT_SEC
    try:
        while time.monotonic() < deadline:
            if frame_png.is_file() and frame_json.is_file():
                # frame.json は PNG より後に書かれるので、両方揃った時点で完了。
                break
            if process.poll() is not None:
                stderr = (process.stderr.read() if process.stderr else "") or ""
                raise ShotError(
                    f"'{ref}' が画像を書く前に終了した（exit {process.returncode}）"
                    f"\n{stderr[-2000:]}"
                )
            time.sleep(POLL_INTERVAL_SEC)
        else:
            raise ShotError(
                f"'{ref}' が {CAPTURE_TIMEOUT_SEC:.0f} 秒以内に frame.png を書かなかった"
            )
        metadata = json.loads(frame_json.read_text(encoding="utf-8"))
        destination = image_path_for(ref)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(frame_png, destination)
    finally:
        process.terminate()
        try:
            process.wait(timeout=10)
        except subprocess.TimeoutExpired:
            process.kill()
        shutil.rmtree(probe_dir, ignore_errors=True)

    size = metadata.get("size", {})
    return {
        "sourceHash": source_hash(package_dir),
        "width": size.get("width"),
        "height": size.get("height"),
        "frame": metadata.get("frame"),
    }


def check(refs: list[str], shots: dict) -> list[str]:
    """撮り直しが要る節を返す（画像が無い / ソースが変わった）。"""
    stale: list[str] = []
    for ref in refs:
        package_dir = CODE_DIR / ref
        if not (package_dir / "Package.swift").is_file():
            raise ShotError(f"'{ref}' に対応する SwiftPM パッケージが無い")
        recorded = shots.get(ref)
        if recorded is None:
            stale.append(f"{ref}: 画像がまだ無い")
        elif not image_path_for(ref).is_file():
            stale.append(f"{ref}: manifest にあるが画像ファイルが無い")
        elif recorded.get("sourceHash") != source_hash(package_dir):
            stale.append(f"{ref}: 撮影後にスケッチが変わった")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="撮らずに鮮度だけ調べる（撮り直しが要れば exit 1）",
    )
    parser.add_argument(
        "--only",
        metavar="REF",
        help="この節だけ撮る（例 01-GettingStarted/03-SketchSkeleton）",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="ソースが変わっていない節も撮り直す",
    )
    args = parser.parse_args()

    try:
        refs = referenced_refs()
        if args.only:
            if args.only not in refs:
                print(
                    f"warning: '{args.only}' は docs/tutorial/*.md から参照されていない",
                    file=sys.stderr,
                )
            refs = [args.only]

        shots = load_manifest()

        if args.check:
            stale = check(refs, shots)
            if not stale:
                print(f"OK: 参照されている {len(refs)} 節すべてに最新の画像がある")
                return 0
            print("error: 実行結果画像が古い:", file=sys.stderr)
            for line in stale:
                print(f"  - {line}", file=sys.stderr)
            print(
                "\n  make tutorial-shots で撮り直してコミットしてください"
                "（GPU が要るのでローカルで実行します）",
                file=sys.stderr,
            )
            return 1

        targets = refs if args.force else [r for r in refs if check([r], shots)]
        if not targets:
            print(f"OK: 参照されている {len(refs)} 節すべてに最新の画像がある")
            return 0

        for ref in targets:
            print(f"capturing {ref}")
            shots[ref] = capture(ref)
            print(f"  -> {image_path_for(ref).relative_to(REPO_ROOT)}")
        save_manifest(shots)
        print(f"\n{len(targets)} 節を撮り直しました。")
    except ShotError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
