#!/usr/bin/env python3
"""API リファレンス（DocC）の日本語版を、英語の出力から生成する。

`docc convert` が吐く `data/documentation/**/*.json`（render JSON）を走査し、
**インライン列を 1 文ずつ**台帳 `docs/reference/i18n/ja.json` の訳へ差し替える。
英語の doc コメントが正典で、日本語リファレンスは画像（ADR-0008）や `llms.txt` と
同じ生成物として扱う（ADR-0011）。

    make docs-ja                                          # 英語版 → 日本語版まで一気に
    python3 scripts/translate-reference.py --check        # 未訳が無いか調べる（CI）
    python3 scripts/translate-reference.py --export out.json   # 未訳を書き出す
    python3 scripts/translate-reference.py --import in.json    # 訳を台帳へ取り込む
    python3 scripts/translate-reference.py --apply --docs-dir .build/docs-ja

## なぜ doc コメントではなく render JSON を訳すのか

Swift-DocC は authoring localization を持たない（swiftlang/swift-docc#648 は 2023-06 起票の
まま open）。日本語版を出すには「英語のソースから日本語のアーカイブを作る」しかない。

翻訳を当てる層は 2 つ考えられた:

1. symbol graph の `docComment` — DocC がパースする**前**の生テキスト。`- Parameter x:` の
   ような構文を翻訳が壊すと、パラメータ表が丸ごと消える
2. render JSON — DocC がパースした**後**の構造化データ。宣言・パラメータ表・コードブロック
   （`codeListing`）・画像は別のノード型なので、インラインの文章だけを触るかぎり
   **構造上壊しようがない**

後者を採る。壊れうる箇所が無いことがコードで保証できるほうが、生成物として扱う前提に合う。

## 翻訳の単位は「テキストノード」ではなく「インライン列」

DocC は 1 つの文を型の違うノードへ刻む。`Sets the fill color.` は

    [{"type":"text","text":"Sets the "},
     {"type":"codeVoice","code":"fill"},
     {"type":"text","text":" color."}]

になる。テキストノードを個別に訳すと `" and "` `" is "` のような切れ端が単独で翻訳器へ渡り、
日本語として繋がらない（実際、英語化済みモジュールだけで 77 件の断片が出た）。

そこで `abstract` / `inlineContent` のような**インライン列をまとめて 1 単位**にし、
テキスト以外のノードをプレースホルダへ退避してから訳す:

    "Sets the ⟦0⟧ color."  →  "⟦0⟧ の色を設定します。"

訳文をプレースホルダで割り戻し、退避したノードを同じ位置へ差し込む。プレースホルダが
訳文から失われていたら**その段落は原文のまま残す**（壊れた訳を出すより英語で出す）。

## 何を訳し、何を訳さないか

`is_translatable()` が下を外す:

- 空白のみ、あるいはラテン文字を含まない断片
- プレースホルダだけの列（インラインコード単体など、訳す中身が無いもの）
- **日本語を含む列** — 訳す必要が無い。移行期（#334 が Core を英語化するまで）は Core の
  説明が日本語のままなので、この規則のおかげで日本語版がそのまま成立する

`heading` は `text` を訳すが `anchor` は書き換えない。表示だけ日本語になり、ページ内リンクの
行き先は英語のアンカーのまま保たれる。

## 翻訳エンジン

台帳の形式はエンジンに依存しない。`--export` / `--import` で外に出して何で訳しても良いし、
`--engine google` は Cloud Translation を直接叩く（`GOOGLE_API_KEY` が要る。月 50 万文字
無料 / 超過 $20 per 1M）。訳が走るのは**英語原文が変わった分だけ**なので、台帳が育つほど
呼び出しは減る。
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Iterator

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_LEDGER = REPO_ROOT / "docs" / "reference" / "i18n" / "ja.json"
DEFAULT_DOCS_DIR = REPO_ROOT / ".build" / "docs"

LEDGER_COMMENT = (
    "Generated by scripts/translate-reference.py. Keys are sha256 of the English source "
    "string; `en` is kept alongside `ja` so the ledger stays reviewable in a diff. "
    "⟦0⟧ style markers stand for inline code, links and other non-text nodes and "
    "must survive translation. English doc comments are the canon (ADR-0011) — edit the "
    "Swift source, not this file."
)

# インライン列とみなす手がかり。この型のノードを含む配列を 1 文として扱う。
INLINE_NODE_TYPES = {
    "text",
    "codeVoice",
    "reference",
    "link",
    "emphasis",
    "strong",
    "image",
    "inlineHead",
    "newTerm",
    "superscript",
    "subscript",
    "strikethrough",
}

_JAPANESE = re.compile(r"[ぁ-んァ-ヶ一-龠]")
_LATIN = re.compile(r"[A-Za-z]")
_PLACEHOLDER = re.compile(r"⟦(\d+)⟧")

GOOGLE_ENDPOINT = "https://translation.googleapis.com/language/translate/v2"
GOOGLE_BATCH = 100


class TranslateError(Exception):
    """翻訳パイプラインが続行できないときに投げる。"""


def placeholder(index: int) -> str:
    return f"⟦{index}⟧"


def serialize_inline(items: list[Any]) -> tuple[str, list[Any]]:
    """インライン列を「訳せる 1 本の文字列」と、退避したノードへ分ける。"""
    parts: list[str] = []
    slots: list[Any] = []
    for item in items:
        if isinstance(item, dict) and item.get("type") == "text" and isinstance(item.get("text"), str):
            parts.append(item["text"])
        else:
            parts.append(placeholder(len(slots)))
            slots.append(item)
    return "".join(parts), slots


def deserialize_inline(translated: str, slots: list[Any]) -> list[Any] | None:
    """訳文をプレースホルダで割り戻し、退避したノードを元の位置へ差し込む。

    プレースホルダが 1 つでも欠けていたら None を返す（呼び出し側は原文を維持する）。
    """
    found = {int(match.group(1)) for match in _PLACEHOLDER.finditer(translated)}
    if found != set(range(len(slots))):
        return None

    rebuilt: list[Any] = []
    cursor = 0
    for match in _PLACEHOLDER.finditer(translated):
        leading = translated[cursor : match.start()]
        if leading:
            rebuilt.append({"type": "text", "text": leading})
        rebuilt.append(slots[int(match.group(1))])
        cursor = match.end()
    trailing = translated[cursor:]
    if trailing:
        rebuilt.append({"type": "text", "text": trailing})
    return rebuilt


def is_translatable(text: str) -> bool:
    """この文字列を訳しにいくべきか。

    「訳さない」と判断したものは原文のまま残る。落とすことはしない。
    """
    stripped = _PLACEHOLDER.sub("", text).strip()
    if not stripped:
        return False
    if _JAPANESE.search(stripped):
        return False
    return bool(_LATIN.search(stripped))


def text_key(text: str) -> str:
    """台帳のキー。原文そのものの指紋。"""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _is_inline_array(value: Any) -> bool:
    return isinstance(value, list) and any(
        isinstance(item, dict) and item.get("type") in INLINE_NODE_TYPES for item in value
    )


def iter_translatable_slots(node: Any) -> Iterator[tuple[Any, Any]]:
    """訳す場所を (容器, キー) で yield する。

    容器が dict でキーが文字列ならインライン列（値は list）か heading の `text`。
    呼び出し側が `container[key]` を差し替えられる。
    """
    if isinstance(node, dict):
        if node.get("type") == "heading" and isinstance(node.get("text"), str):
            yield node, "text"
        for key, value in node.items():
            if _is_inline_array(value):
                yield node, key
            else:
                yield from iter_translatable_slots(value)
    elif isinstance(node, list):
        for item in node:
            yield from iter_translatable_slots(item)


def source_of(container: Any, key: Any) -> tuple[str, list[Any]] | None:
    """訳す場所から、翻訳にかける文字列と退避ノードを取り出す。"""
    value = container[key]
    if isinstance(value, str):
        return value, []
    if isinstance(value, list):
        return serialize_inline(value)
    return None


def render_json_files(docs_dir: Path) -> list[Path]:
    """DocC 出力の render JSON を集める。"""
    data_dir = docs_dir / "data" / "documentation"
    if not data_dir.is_dir():
        raise TranslateError(
            f"render JSON が見つかりません: {data_dir}\n"
            "先に `make docs` で英語版を作ってください。"
        )
    return sorted(data_dir.rglob("*.json"))


def collect_sources(docs_dir: Path) -> dict[str, str]:
    """出力全体から、訳す必要のある原文を集める（キー → 原文）。"""
    sources: dict[str, str] = {}
    for path in render_json_files(docs_dir):
        document = json.loads(path.read_text(encoding="utf-8"))
        for container, key in iter_translatable_slots(document):
            extracted = source_of(container, key)
            if extracted is None:
                continue
            text, _ = extracted
            if is_translatable(text):
                sources[text_key(text)] = text
    return sources


def load_ledger(path: Path) -> dict[str, dict[str, str]]:
    """台帳を読む。無ければ空で始める。"""
    if not path.is_file():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    entries = payload.get("entries", {})
    if not isinstance(entries, dict):
        raise TranslateError(f"台帳の entries が壊れています: {path}")
    return entries


def save_ledger(path: Path, entries: dict[str, dict[str, str]]) -> None:
    """台帳を書く。差分が読めるようキー順に並べ、日本語はそのまま出す。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "comment": LEDGER_COMMENT,
        "entries": {key: entries[key] for key in sorted(entries)},
    }
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def missing_keys(sources: dict[str, str], entries: dict[str, dict[str, str]]) -> dict[str, str]:
    """台帳にまだ訳が無い原文（キー → 原文）。"""
    return {key: text for key, text in sources.items() if not entries.get(key, {}).get("ja")}


def apply_ledger(docs_dir: Path, entries: dict[str, dict[str, str]]) -> tuple[int, int, int]:
    """出力の render JSON を台帳の訳で書き換える。

    Returns:
        (差し替えた箇所, 訳が無くて原文のまま残した箇所, プレースホルダが壊れて捨てた訳)
    """
    replaced = 0
    left = 0
    broken = 0
    for path in render_json_files(docs_dir):
        document = json.loads(path.read_text(encoding="utf-8"))
        touched = False
        for container, key in iter_translatable_slots(document):
            extracted = source_of(container, key)
            if extracted is None:
                continue
            text, slots = extracted
            if not is_translatable(text):
                continue
            translation = entries.get(text_key(text), {}).get("ja")
            if not translation:
                left += 1
                continue
            if isinstance(container[key], str):
                container[key] = translation
                replaced += 1
                touched = True
                continue
            rebuilt = deserialize_inline(translation, slots)
            if rebuilt is None:
                broken += 1
                continue
            container[key] = rebuilt
            replaced += 1
            touched = True
        if touched:
            path.write_text(
                json.dumps(document, ensure_ascii=False, separators=(",", ":")),
                encoding="utf-8",
            )
    return replaced, left, broken


def translate_google(texts: list[str], api_key: str) -> list[str]:
    """Cloud Translation で英語 → 日本語。バッチで叩く。"""
    results: list[str] = []
    for start in range(0, len(texts), GOOGLE_BATCH):
        batch = texts[start : start + GOOGLE_BATCH]
        body = [("q", text) for text in batch]
        body += [("source", "en"), ("target", "ja"), ("format", "text")]
        request = urllib.request.Request(
            f"{GOOGLE_ENDPOINT}?key={urllib.parse.quote(api_key)}",
            data=urllib.parse.urlencode(body).encode("utf-8"),
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=60) as response:
            payload = json.loads(response.read().decode("utf-8"))
        translations = payload.get("data", {}).get("translations", [])
        if len(translations) != len(batch):
            raise TranslateError(
                f"翻訳 API の応答数が合いません（要求 {len(batch)} / 応答 {len(translations)}）"
            )
        results.extend(item["translatedText"] for item in translations)
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--docs-dir",
        type=Path,
        default=DEFAULT_DOCS_DIR,
        help="DocC 出力のルート（既定 .build/docs）",
    )
    parser.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER, help="対訳台帳の場所")
    parser.add_argument(
        "--check",
        action="store_true",
        help="未訳が残っていないか調べる（翻訳も書き換えもしない・CI 用）",
    )
    parser.add_argument("--export", type=Path, help="未訳の原文を JSON に書き出す")
    parser.add_argument("--import", dest="import_path", type=Path, help="訳を台帳へ取り込む")
    parser.add_argument(
        "--apply", action="store_true", help="台帳の訳を --docs-dir の render JSON へ当てる"
    )
    parser.add_argument(
        "--engine",
        choices=["google"],
        help="未訳をこのエンジンで訳して台帳へ入れる（GOOGLE_API_KEY が要る）",
    )
    parser.add_argument(
        "--copy-from",
        type=Path,
        help="--docs-dir が無いとき、ここから複製してから当てる（英語版 → 日本語版）",
    )
    args = parser.parse_args()

    try:
        entries = load_ledger(args.ledger)

        if args.import_path:
            incoming = json.loads(args.import_path.read_text(encoding="utf-8"))
            added = 0
            skipped = 0
            for key, value in incoming.get("entries", incoming).items():
                english = value.get("en") if isinstance(value, dict) else None
                japanese = value.get("ja") if isinstance(value, dict) else value
                if not japanese:
                    continue
                if english and text_key(english) != key:
                    raise TranslateError(f"取り込むキーが原文と合いません: {key}（en={english!r}）")
                if english:
                    expected = {int(m.group(1)) for m in _PLACEHOLDER.finditer(english)}
                    got = {int(m.group(1)) for m in _PLACEHOLDER.finditer(japanese)}
                    if expected != got:
                        skipped += 1
                        continue
                entries[key] = {"en": english or entries.get(key, {}).get("en", ""), "ja": japanese}
                added += 1
            save_ledger(args.ledger, entries)
            print(f"台帳へ {added} 件を取り込みました: {args.ledger}")
            if skipped:
                print(f"プレースホルダが合わない {skipped} 件は捨てました")
            return 0

        if args.copy_from:
            if args.docs_dir.exists():
                shutil.rmtree(args.docs_dir)
            shutil.copytree(args.copy_from, args.docs_dir)

        sources = collect_sources(args.docs_dir)
        missing = missing_keys(sources, entries)

        if args.engine == "google":
            api_key = os.environ.get("GOOGLE_API_KEY")
            if not api_key:
                raise TranslateError("GOOGLE_API_KEY が設定されていません")
            if missing:
                keys = list(missing)
                translated = translate_google([missing[key] for key in keys], api_key)
                for key, japanese in zip(keys, translated):
                    entries[key] = {"en": missing[key], "ja": japanese}
                save_ledger(args.ledger, entries)
                print(f"{len(keys)} 件を翻訳して台帳へ入れました")
                missing = {}

        if args.export:
            payload = {
                "comment": (
                    "Untranslated strings from the English DocC output. Fill in `ja` for each "
                    "entry and feed it back with --import. Markers like ⟦0⟧ stand for inline "
                    "code and links: keep every one of them in the translation, or the entry "
                    "is dropped."
                ),
                "entries": {
                    key: {"en": text, "ja": ""}
                    for key, text in sorted(missing.items(), key=lambda kv: kv[1])
                },
            }
            args.export.parent.mkdir(parents=True, exist_ok=True)
            args.export.write_text(
                json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
            )
            print(f"未訳 {len(missing)} 件を書き出しました: {args.export}")
            return 0

        if args.check:
            total = len(sources)
            if missing:
                print(
                    f"未訳が {len(missing)} 件あります（翻訳対象 {total} 件）。\n"
                    "`make reference-i18n` で台帳を更新してください。例:"
                )
                for key in list(missing)[:5]:
                    print(f"  - {missing[key]!r}")
                return 1
            print(f"台帳は最新です（翻訳対象 {total} 件）。")
            return 0

        if args.apply:
            replaced, left, broken = apply_ledger(args.docs_dir, entries)
            print(f"{replaced} 箇所を日本語へ差し替えました（未訳のまま残した: {left}）")
            if broken:
                print(f"プレースホルダが壊れた {broken} 箇所は原文のまま残しました")
            return 0

        parser.print_help()
        return 2
    except TranslateError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
